CREATE OR REPLACE VIEW "TASY"."LOCATION" AS 
SELECT SA.CD_SETOR_ATENDIMENTO AS "location_code",
       UA.CD_UNIDADE_BASICA AS "location_place_code",
       SA.DS_SETOR_ATENDIMENTO AS "location_name",
       TA.DS_TIPO_ACOMODACAO AS "location_type",
       TO_CHAR(SA.DT_ATUALIZACAO_NREC, 'YYYY-MM-DD') AS "created_date",
       TO_CHAR(SA.DT_ATUALIZACAO, 'YYYY-MM-DD') AS "updated_date",
       NULL AS "location_reason",
       SA.NM_USUARIO AS "location_responsible",
       SA.CD_ESTABELECIMENTO AS "location_organization_code"
  FROM TASY.SETOR_ATENDIMENTO SA
       JOIN TASY.UNIDADE_ATENDIMENTO UA ON SA.CD_SETOR_ATENDIMENTO = UA.CD_SETOR_ATENDIMENTO
       JOIN TASY.TIPO_ACOMODACAO TA ON UA.CD_TIPO_ACOMODACAO = TA.CD_TIPO_ACOMODACAO;