CREATE OR REPLACE VIEW "DBAMV"."PATIENT"
(
	"patient_code",
	"prontuary_patient",
	"patient_name",
	"patient_social_name",
	"patient_blood_type",
	"patient_birth_date",
	"patient_sex",
	"patient_gender",
	"patient_mother_name",
	"patient_father_name",
	"patient_primary_document",
	"patient_secondary_document",
	"patient_third_document",
	"patient_fourth_document",
	"patient_fifth_document",
	"patient_sixth_document",
	"patient_seventh_document", 
	"patient_eighth_document",
	"patient_ninth_document",
	"patient_tenth_document",
	"patient_relationship",
	"patient_race",
	"patient_ethnicity",
	"patient_religion",
	"patient_profession",
	"patient_education",
	"patient_nationality",
	"patient_naturality",
	"patient_accommodation",
	"patient_marital_status",
	"patient_email",
	"patient_ddd_phone",
	"patient_phone",
	"patient_ddd_mobile",
	"patient_mobile",
	"patient_ddd_phone_contact",
	"patient_phone_contact",
	"patient_addres",
	"patient_number",
	"patient_complement",
	"patient_city",
	"patient_neighborhood",
	"patient_state",
	"patient_country",
	"patient_zipcode",
	"patient_bank_number",
	"patient_agency",
	"patient_account",
	"patient_account_type",
	"patient_related_person",
	"created_date",
	"created_time",
	"updated_date",
	"updated_time",
	"patient_status",
	"patient_blocked"
) AS
SELECT P.CD_PACIENTE AS "patient_code",
       P.CD_PACIENTE AS "prontuary_patient",
       P.NM_PACIENTE AS "patient_name",
	   P.NM_SOCIAL_PACIENTE AS "patient_social_name",
	   P.TP_SANGUINEO AS "patient_blood_type",
	   TO_CHAR(P.DT_NASCIMENTO, 'YYYY-MM-DD') AS "patient_birth_date",
	   P.TP_SEXO AS "patient_sex",
	   NULL AS "patient_gender",
	   P.NM_MAE AS "patient_mother_name",
	   P.NM_PAI AS "patient_father_name",
	   P.NR_CPF AS "patient_primary_document",
	   P.NR_IDENTIDADE AS "patient_secondary_document",
	   NULL AS "patient_third_document",
	   P.NR_CNS AS "patient_fourth_document",
	   NULL AS "patient_fifth_document",
	   P.NR_DOCUMENTO_ESTRANGEIRO  AS "patient_sixth_document",
	   NULL AS "patient_seventh_document", 
	   P.NR_RG_NASC AS "patient_eighth_document",
	   P.NR_DECLARACAO_NASCIDO_VIVO  AS "patient_ninth_document",
	   P.NR_CPF_TUTOR AS "patient_tenth_document",
	   TP.DS_TIP_PAREN AS "patient_relationship",
	   DECODE(P.TP_COR,
	          'R', 'parda',
			  'P', 'preta',
			  'I', 'indigena',
			  'B', 'branca',
			  'A', 'amarela',
			  'S', 'sem informacao', NULL) AS "patient_race",
	   ET.DS_ETNIA AS "patient_ethnicity",
       R.DS_RELIGIAO AS "patient_religion",
	   PROF.NM_PROFISSAO AS "patient_profession",
	   GI.DS_GRAU_INS AS "patient_education",
	   C.DS_CIDADANIA AS "patient_nationality",
	   CNAT.NM_CIDADE AS "patient_naturality",
	   TM.DS_TIP_MOR AS "patient_accommodation",
	   DECODE(TP_ESTADO_CIVIL,
	          'S', 'solteiro',
			  'C', 'casado',
			  'V', 'viuvo',
			  'D', 'desquitado',
			  'I', 'divorciado',
			  'U', 'uniao-estavel',
			  'G', 'ignorado') AS "patient_marital_status",
       P.EMAIL AS "patient_email",
	   TO_CHAR(P.NR_DDD_FONE) AS "patient_ddd_phone",
	   P.NR_FONE AS "patient_phone",
	   TO_CHAR(P.NR_DDD_CELULAR) AS "patient_ddd_mobile",
	   P.NR_CELULAR AS "patient_mobile",
	   TO_CHAR(P.NR_DDD_FONE_COMERCIAL) AS "patient_ddd_phone_contact",
	   TO_CHAR(P.NR_FONE_COMERCIAL) AS "patient_phone_contact",
	   P.DS_ENDERECO AS "patient_addres",
	   P.NR_ENDERECO AS "patient_number",
	   P.DS_COMPLEMENTO AS "patient_complement",
	   CRES.NM_CIDADE AS "patient_city",
	   P.NM_BAIRRO AS "patient_neighborhood",
	   CRES.CD_UF AS "patient_state",
	   PA.NM_PAIS AS "patient_country",
	   P.NR_CEP AS "patient_zipcode",
	   P.CD_BANCO  AS "patient_bank_number",
	   P.NR_AGENCIA AS "patient_agency",
	   P.NR_CONTA AS "patient_account",
	   NULL AS "patient_account_type",
	   P.NM_TUTOR AS "patient_related_person",
	   TO_CHAR(P.DT_CADASTRO, 'YYYY-MM-DD') AS "created_date",
	   TO_CHAR(P.DT_CADASTRO, 'HH24:MI:SS') AS "created_time", 
	   TO_CHAR(P.DT_ULTIMA_ATUALIZACAO, 'YYYY-MM-DD') AS "updated_date",  
	   TO_CHAR(P.DT_ULTIMA_ATUALIZACAO, 'HH24:MI:SS') AS "updated_time",
	   NULL AS "patient_status",
	   NULL AS "patient_blocked"
  FROM DBAMV.PACIENTE P
  LEFT JOIN DBAMV.PROFISSAO PROF ON P.CD_PROFISSAO = PROF.CD_PROFISSAO
  LEFT JOIN DBAMV.GRAU_INS GI ON P.CD_GRAU_INS = GI.CD_GRAU_INS
  LEFT JOIN DBAMV.CIDADANIAS C ON P.CD_CIDADANIA = C.CD_CIDADANIA
  LEFT JOIN DBAMV.CIDADE CRES ON P.CD_CIDADE = CRES.CD_CIDADE
  LEFT JOIN DBAMV.CIDADE CNAT ON P.CD_NATURALIDADE = CNAT.CD_CIDADE
  LEFT JOIN DBAMV.TIP_MOR TM ON P.CD_TIP_MOR = TM.CD_TIP_MOR
  LEFT JOIN DBAMV.TIP_PAREN TP  ON P.CD_TIP_PAREN = TP.CD_TIP_PAREN 
  LEFT JOIN DBAMV.PAIS PA ON PA.CD_PAIS = P.CD_PAIS
  LEFT JOIN DBAMV.ETNIA ET ON ET.CD_ETNIA = P.CD_ETNIA
  LEFT JOIN DBAMV.RELIGIAO R ON P.CD_RELIGIAO = R.CD_RELIGIAO;
